# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(1384, 870)
        self.stepButton = QtWidgets.QPushButton(mainwindow)
        self.stepButton.setGeometry(QtCore.QRect(530, 574, 111, 32))
        self.stepButton.setObjectName("stepButton")
        self.tabs = QtWidgets.QTabWidget(mainwindow)
        self.tabs.setGeometry(QtCore.QRect(530, 100, 811, 421))
        self.tabs.setTabsClosable(False)
        self.tabs.setObjectName("tabs")
        self.codeTab = QtWidgets.QWidget()
        self.codeTab.setObjectName("codeTab")
        self.codeEditor = CodeEditor(self.codeTab)
        self.codeEditor.setGeometry(QtCore.QRect(0, 0, 811, 391))
        self.codeEditor.setObjectName("codeEditor")
        self.tabs.addTab(self.codeTab, "")
        self.animationTab = QtWidgets.QWidget()
        self.animationTab.setObjectName("animationTab")
        self.animationView = QtWidgets.QGraphicsView(self.animationTab)
        self.animationView.setGeometry(QtCore.QRect(0, 0, 811, 391))
        self.animationView.setObjectName("animationView")
        self.tabs.addTab(self.animationTab, "")
        self.stepBreakpointButton = QtWidgets.QPushButton(mainwindow)
        self.stepBreakpointButton.setGeometry(QtCore.QRect(1140, 560, 191, 32))
        self.stepBreakpointButton.setObjectName("stepBreakpointButton")
        self.line_2 = QtWidgets.QFrame(mainwindow)
        self.line_2.setGeometry(QtCore.QRect(530, 630, 801, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.title = QtWidgets.QLabel(mainwindow)
        self.title.setGeometry(QtCore.QRect(440, 0, 561, 111))
        self.title.setObjectName("title")
        self.line_1 = QtWidgets.QFrame(mainwindow)
        self.line_1.setGeometry(QtCore.QRect(540, 530, 801, 20))
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.importButton = QtWidgets.QPushButton(mainwindow)
        self.importButton.setGeometry(QtCore.QRect(1200, 10, 113, 32))
        self.importButton.setObjectName("importButton")
        self.exportButton = QtWidgets.QPushButton(mainwindow)
        self.exportButton.setGeometry(QtCore.QRect(1200, 40, 113, 32))
        self.exportButton.setObjectName("exportButton")
        self.currentBreakpointsLabel = QtWidgets.QLabel(mainwindow)
        self.currentBreakpointsLabel.setGeometry(QtCore.QRect(980, 550, 131, 21))
        self.currentBreakpointsLabel.setObjectName("currentBreakpointsLabel")
        self.addBreakpointButton = QtWidgets.QPushButton(mainwindow)
        self.addBreakpointButton.setGeometry(QtCore.QRect(760, 554, 141, 32))
        self.addBreakpointButton.setObjectName("addBreakpointButton")
        self.stepNCyclesButton = QtWidgets.QPushButton(mainwindow)
        self.stepNCyclesButton.setGeometry(QtCore.QRect(530, 604, 121, 32))
        self.stepNCyclesButton.setObjectName("stepNCyclesButton")
        self.resetButton = QtWidgets.QPushButton(mainwindow)
        self.resetButton.setGeometry(QtCore.QRect(1200, 70, 113, 32))
        self.resetButton.setObjectName("resetButton")
        self.currentCycleLabel = QtWidgets.QLabel(mainwindow)
        self.currentCycleLabel.setGeometry(QtCore.QRect(550, 550, 131, 21))
        self.currentCycleLabel.setObjectName("currentCycleLabel")
        self.stepCompletionButton = QtWidgets.QPushButton(mainwindow)
        self.stepCompletionButton.setGeometry(QtCore.QRect(1140, 590, 191, 32))
        self.stepCompletionButton.setObjectName("stepCompletionButton")
        self.line = QtWidgets.QFrame(mainwindow)
        self.line.setGeometry(QtCore.QRect(740, 550, 31, 81))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dataTabs = QtWidgets.QTabWidget(mainwindow)
        self.dataTabs.setGeometry(QtCore.QRect(10, 100, 501, 751))
        self.dataTabs.setObjectName("dataTabs")
        self.registerTab = QtWidgets.QWidget()
        self.registerTab.setObjectName("registerTab")
        self.registerTable = QtWidgets.QTableWidget(self.registerTab)
        self.registerTable.setEnabled(True)
        self.registerTable.setGeometry(QtCore.QRect(0, 0, 491, 721))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerTable.sizePolicy().hasHeightForWidth())
        self.registerTable.setSizePolicy(sizePolicy)
        self.registerTable.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.registerTable.setFont(font)
        self.registerTable.setAutoFillBackground(False)
        self.registerTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.registerTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.registerTable.setAlternatingRowColors(True)
        self.registerTable.setShowGrid(True)
        self.registerTable.setWordWrap(True)
        self.registerTable.setRowCount(64)
        self.registerTable.setObjectName("registerTable")
        self.registerTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setItem(32, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setItem(32, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setItem(33, 0, item)
        self.registerTable.horizontalHeader().setVisible(True)
        self.registerTable.horizontalHeader().setCascadingSectionResizes(True)
        self.registerTable.horizontalHeader().setDefaultSectionSize(222)
        self.registerTable.horizontalHeader().setStretchLastSection(True)
        self.registerTable.verticalHeader().setVisible(True)
        self.registerTable.verticalHeader().setDefaultSectionSize(22)
        self.dataTabs.addTab(self.registerTab, "")
        self.memoryTab = QtWidgets.QWidget()
        self.memoryTab.setObjectName("memoryTab")
        self.memoryTable = QtWidgets.QTableWidget(self.memoryTab)
        self.memoryTable.setEnabled(True)
        self.memoryTable.setGeometry(QtCore.QRect(0, 0, 480, 701))
        self.memoryTable.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(11)
        self.memoryTable.setFont(font)
        self.memoryTable.setAutoFillBackground(False)
        self.memoryTable.setAlternatingRowColors(True)
        self.memoryTable.setRowCount(256)
        self.memoryTable.setObjectName("memoryTable")
        self.memoryTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTable.setItem(0, 1, item)
        self.memoryTable.horizontalHeader().setDefaultSectionSize(222)
        self.memoryTable.verticalHeader().setVisible(False)
        self.memoryTable.verticalHeader().setDefaultSectionSize(22)
        self.dataTabs.addTab(self.memoryTab, "")
        self.cacheTab = QtWidgets.QWidget()
        self.cacheTab.setObjectName("cacheTab")
        self.cacheTable = QtWidgets.QTableWidget(self.cacheTab)
        self.cacheTable.setGeometry(QtCore.QRect(0, 0, 480, 701))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(11)
        self.cacheTable.setFont(font)
        self.cacheTable.setAlternatingRowColors(True)
        self.cacheTable.setRowCount(64)
        self.cacheTable.setObjectName("cacheTable")
        self.cacheTable.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cacheTable.setItem(5, 3, item)
        self.cacheTable.horizontalHeader().setCascadingSectionResizes(True)
        self.cacheTable.horizontalHeader().setDefaultSectionSize(50)
        self.cacheTable.horizontalHeader().setSortIndicatorShown(False)
        self.cacheTable.horizontalHeader().setStretchLastSection(True)
        self.cacheTable.verticalHeader().setVisible(False)
        self.cacheTable.verticalHeader().setDefaultSectionSize(22)
        self.cacheTable.verticalHeader().setHighlightSections(True)
        self.cacheTable.verticalHeader().setSortIndicatorShown(False)
        self.cacheTable.verticalHeader().setStretchLastSection(False)
        self.dataTabs.addTab(self.cacheTab, "")
        self.layoutWidget_7 = QtWidgets.QWidget(mainwindow)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 70, 229, 26))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.memoryDisplayLayout = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.memoryDisplayLayout.setContentsMargins(0, 0, 0, 0)
        self.memoryDisplayLayout.setObjectName("memoryDisplayLayout")
        self.memoryDisplayLabel = QtWidgets.QLabel(self.layoutWidget_7)
        self.memoryDisplayLabel.setObjectName("memoryDisplayLabel")
        self.memoryDisplayLayout.addWidget(self.memoryDisplayLabel)
        self.memoryDisplayBox = QtWidgets.QComboBox(self.layoutWidget_7)
        self.memoryDisplayBox.setObjectName("memoryDisplayBox")
        self.memoryDisplayBox.addItem("")
        self.memoryDisplayBox.addItem("")
        self.memoryDisplayBox.addItem("")
        self.memoryDisplayLayout.addWidget(self.memoryDisplayBox)
        self.removeBreakpointButton = QtWidgets.QPushButton(mainwindow)
        self.removeBreakpointButton.setGeometry(QtCore.QRect(760, 594, 141, 32))
        self.removeBreakpointButton.setObjectName("removeBreakpointButton")
        self.line_3 = QtWidgets.QFrame(mainwindow)
        self.line_3.setGeometry(QtCore.QRect(1120, 550, 31, 81))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groupBox = QtWidgets.QGroupBox(mainwindow)
        self.groupBox.setGeometry(QtCore.QRect(510, 630, 861, 231))
        self.groupBox.setObjectName("groupBox")
        self.setConfigurationButton = QtWidgets.QPushButton(self.groupBox)
        self.setConfigurationButton.setGeometry(QtCore.QRect(300, 200, 201, 32))
        self.setConfigurationButton.setObjectName("setConfigurationButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 204, 155))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.L1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.L1.setContentsMargins(0, 0, 0, 0)
        self.L1.setObjectName("L1")
        self.L1Enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.L1Enabled.setChecked(True)
        self.L1Enabled.setObjectName("L1Enabled")
        self.L1.addWidget(self.L1Enabled)
        self.L1AssociativityLayout = QtWidgets.QHBoxLayout()
        self.L1AssociativityLayout.setObjectName("L1AssociativityLayout")
        self.L1AssociativityLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.L1AssociativityLabel.setObjectName("L1AssociativityLabel")
        self.L1AssociativityLayout.addWidget(self.L1AssociativityLabel)
        self.L1Associativity = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.L1Associativity.setObjectName("L1Associativity")
        self.L1Associativity.addItem("")
        self.L1Associativity.addItem("")
        self.L1Associativity.addItem("")
        self.L1Associativity.addItem("")
        self.L1Associativity.addItem("")
        self.L1Associativity.addItem("")
        self.L1Associativity.addItem("")
        self.L1AssociativityLayout.addWidget(self.L1Associativity)
        self.L1.addLayout(self.L1AssociativityLayout)
        self.L1LinesLayout = QtWidgets.QHBoxLayout()
        self.L1LinesLayout.setObjectName("L1LinesLayout")
        self.L1LinesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.L1LinesLabel.setObjectName("L1LinesLabel")
        self.L1LinesLayout.addWidget(self.L1LinesLabel)
        self.L1Lines = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.L1Lines.setObjectName("L1Lines")
        self.L1LinesLayout.addWidget(self.L1Lines)
        self.L1.addLayout(self.L1LinesLayout)
        self.L1WordsPerLineLayout = QtWidgets.QHBoxLayout()
        self.L1WordsPerLineLayout.setObjectName("L1WordsPerLineLayout")
        self.L1WordsPerLineLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.L1WordsPerLineLabel.setObjectName("L1WordsPerLineLabel")
        self.L1WordsPerLineLayout.addWidget(self.L1WordsPerLineLabel)
        self.L1WordsPerLine = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.L1WordsPerLine.setObjectName("L1WordsPerLine")
        self.L1WordsPerLine.addItem("")
        self.L1WordsPerLine.addItem("")
        self.L1WordsPerLine.addItem("")
        self.L1WordsPerLine.addItem("")
        self.L1WordsPerLine.addItem("")
        self.L1WordsPerLine.addItem("")
        self.L1WordsPerLine.addItem("")
        self.L1WordsPerLine.setItemText(6, "")
        self.L1WordsPerLineLayout.addWidget(self.L1WordsPerLine)
        self.L1.addLayout(self.L1WordsPerLineLayout)
        self.L1CyclesLayout = QtWidgets.QHBoxLayout()
        self.L1CyclesLayout.setObjectName("L1CyclesLayout")
        self.L1CyclesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.L1CyclesLabel.setObjectName("L1CyclesLabel")
        self.L1CyclesLayout.addWidget(self.L1CyclesLabel)
        self.L1Cycles = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.L1Cycles.setObjectName("L1Cycles")
        self.L1CyclesLayout.addWidget(self.L1Cycles)
        self.L1.addLayout(self.L1CyclesLayout)
        self.writePolicyLabel = QtWidgets.QLabel(self.groupBox)
        self.writePolicyLabel.setGeometry(QtCore.QRect(630, 30, 121, 26))
        self.writePolicyLabel.setObjectName("writePolicyLabel")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 30, 204, 155))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.L2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.L2.setContentsMargins(0, 0, 0, 0)
        self.L2.setObjectName("L2")
        self.L2Enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.L2Enabled.setObjectName("L2Enabled")
        self.L2.addWidget(self.L2Enabled)
        self.L2AssociativityLayout = QtWidgets.QHBoxLayout()
        self.L2AssociativityLayout.setObjectName("L2AssociativityLayout")
        self.L2AssociativityLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.L2AssociativityLabel.setObjectName("L2AssociativityLabel")
        self.L2AssociativityLayout.addWidget(self.L2AssociativityLabel)
        self.L2Associativity = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.L2Associativity.setObjectName("L2Associativity")
        self.L2Associativity.addItem("")
        self.L2Associativity.addItem("")
        self.L2Associativity.addItem("")
        self.L2Associativity.addItem("")
        self.L2Associativity.addItem("")
        self.L2Associativity.addItem("")
        self.L2Associativity.addItem("")
        self.L2AssociativityLayout.addWidget(self.L2Associativity)
        self.L2.addLayout(self.L2AssociativityLayout)
        self.L2LinesLayout = QtWidgets.QHBoxLayout()
        self.L2LinesLayout.setObjectName("L2LinesLayout")
        self.L2LinesLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.L2LinesLabel.setObjectName("L2LinesLabel")
        self.L2LinesLayout.addWidget(self.L2LinesLabel)
        self.L2Lines = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.L2Lines.setObjectName("L2Lines")
        self.L2LinesLayout.addWidget(self.L2Lines)
        self.L2.addLayout(self.L2LinesLayout)
        self.L2WordsPerLineLayout = QtWidgets.QHBoxLayout()
        self.L2WordsPerLineLayout.setObjectName("L2WordsPerLineLayout")
        self.L2WordsPerLineLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.L2WordsPerLineLabel.setObjectName("L2WordsPerLineLabel")
        self.L2WordsPerLineLayout.addWidget(self.L2WordsPerLineLabel)
        self.L2WordsPerLine = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.L2WordsPerLine.setObjectName("L2WordsPerLine")
        self.L2WordsPerLine.addItem("")
        self.L2WordsPerLine.addItem("")
        self.L2WordsPerLine.addItem("")
        self.L2WordsPerLine.addItem("")
        self.L2WordsPerLine.addItem("")
        self.L2WordsPerLine.addItem("")
        self.L2WordsPerLineLayout.addWidget(self.L2WordsPerLine)
        self.L2.addLayout(self.L2WordsPerLineLayout)
        self.L2CyclesLayout = QtWidgets.QHBoxLayout()
        self.L2CyclesLayout.setObjectName("L2CyclesLayout")
        self.L2CyclesLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.L2CyclesLabel.setObjectName("L2CyclesLabel")
        self.L2CyclesLayout.addWidget(self.L2CyclesLabel)
        self.L2Cycles = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.L2Cycles.setObjectName("L2Cycles")
        self.L2CyclesLayout.addWidget(self.L2Cycles)
        self.L2.addLayout(self.L2CyclesLayout)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setGeometry(QtCore.QRect(580, 30, 61, 151))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.writePolicyBox = QtWidgets.QComboBox(self.groupBox)
        self.writePolicyBox.setGeometry(QtCore.QRect(710, 30, 131, 26))
        self.writePolicyBox.setObjectName("writePolicyBox")
        self.writePolicyBox.addItem("")
        self.writePolicyBox.addItem("")
        self.evictionPolicyLabel = QtWidgets.QLabel(self.groupBox)
        self.evictionPolicyLabel.setGeometry(QtCore.QRect(630, 60, 121, 26))
        self.evictionPolicyLabel.setObjectName("evictionPolicyLabel")
        self.evictionPolicyBox = QtWidgets.QComboBox(self.groupBox)
        self.evictionPolicyBox.setGeometry(QtCore.QRect(730, 60, 111, 26))
        self.evictionPolicyBox.setObjectName("evictionPolicyBox")
        self.evictionPolicyBox.addItem("")
        self.evictionPolicyBox.addItem("")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(410, 30, 204, 155))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.L3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.L3.setContentsMargins(0, 0, 0, 0)
        self.L3.setObjectName("L3")
        self.L3Enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.L3Enabled.setObjectName("L3Enabled")
        self.L3.addWidget(self.L3Enabled)
        self.L3AssociativityLayout = QtWidgets.QHBoxLayout()
        self.L3AssociativityLayout.setObjectName("L3AssociativityLayout")
        self.L3AssociativityLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.L3AssociativityLabel.setObjectName("L3AssociativityLabel")
        self.L3AssociativityLayout.addWidget(self.L3AssociativityLabel)
        self.L3Associativity = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.L3Associativity.setObjectName("L3Associativity")
        self.L3Associativity.addItem("")
        self.L3Associativity.addItem("")
        self.L3Associativity.addItem("")
        self.L3Associativity.addItem("")
        self.L3Associativity.addItem("")
        self.L3Associativity.addItem("")
        self.L3Associativity.addItem("")
        self.L3AssociativityLayout.addWidget(self.L3Associativity)
        self.L3.addLayout(self.L3AssociativityLayout)
        self.L3LinesLayout = QtWidgets.QHBoxLayout()
        self.L3LinesLayout.setObjectName("L3LinesLayout")
        self.L3LinesLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.L3LinesLabel.setObjectName("L3LinesLabel")
        self.L3LinesLayout.addWidget(self.L3LinesLabel)
        self.L3Lines = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.L3Lines.setObjectName("L3Lines")
        self.L3LinesLayout.addWidget(self.L3Lines)
        self.L3.addLayout(self.L3LinesLayout)
        self.L3WordsPerLineLayout = QtWidgets.QHBoxLayout()
        self.L3WordsPerLineLayout.setObjectName("L3WordsPerLineLayout")
        self.L3WordsPerLineLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.L3WordsPerLineLabel.setObjectName("L3WordsPerLineLabel")
        self.L3WordsPerLineLayout.addWidget(self.L3WordsPerLineLabel)
        self.L3WordsPerLine = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.L3WordsPerLine.setObjectName("L3WordsPerLine")
        self.L3WordsPerLine.addItem("")
        self.L3WordsPerLine.addItem("")
        self.L3WordsPerLine.addItem("")
        self.L3WordsPerLine.addItem("")
        self.L3WordsPerLine.addItem("")
        self.L3WordsPerLine.addItem("")
        self.L3WordsPerLineLayout.addWidget(self.L3WordsPerLine)
        self.L3.addLayout(self.L3WordsPerLineLayout)
        self.L3CyclesLayout = QtWidgets.QHBoxLayout()
        self.L3CyclesLayout.setObjectName("L3CyclesLayout")
        self.L3CyclesLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.L3CyclesLabel.setObjectName("L3CyclesLabel")
        self.L3CyclesLayout.addWidget(self.L3CyclesLabel)
        self.L3Cycles = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.L3Cycles.setObjectName("L3Cycles")
        self.L3CyclesLayout.addWidget(self.L3Cycles)
        self.L3.addLayout(self.L3CyclesLayout)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(630, 100, 221, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.memory = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.memory.setContentsMargins(0, 0, 0, 0)
        self.memory.setObjectName("memory")
        self.memoryLinesLayout = QtWidgets.QHBoxLayout()
        self.memoryLinesLayout.setObjectName("memoryLinesLayout")
        self.memoryLinesLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.memoryLinesLabel.setObjectName("memoryLinesLabel")
        self.memoryLinesLayout.addWidget(self.memoryLinesLabel)
        self.memoryLines = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.memoryLines.setObjectName("memoryLines")
        self.memoryLinesLayout.addWidget(self.memoryLines)
        self.memory.addLayout(self.memoryLinesLayout)
        self.memoryCyclesLayout = QtWidgets.QHBoxLayout()
        self.memoryCyclesLayout.setObjectName("memoryCyclesLayout")
        self.memoryCyclesLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.memoryCyclesLabel.setObjectName("memoryCyclesLabel")
        self.memoryCyclesLayout.addWidget(self.memoryCyclesLabel)
        self.memoryCycles = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.memoryCycles.setObjectName("memoryCycles")
        self.memoryCyclesLayout.addWidget(self.memoryCycles)
        self.memory.addLayout(self.memoryCyclesLayout)
        self.pipelineEnabledButton = QtWidgets.QCheckBox(self.groupBox)
        self.pipelineEnabledButton.setGeometry(QtCore.QRect(630, 170, 141, 20))
        self.pipelineEnabledButton.setObjectName("pipelineEnabledButton")
        self.NCyclesLabel = QtWidgets.QLabel(mainwindow)
        self.NCyclesLabel.setGeometry(QtCore.QRect(655, 610, 16, 21))
        self.NCyclesLabel.setObjectName("NCyclesLabel")
        self.stepSize = QtWidgets.QLineEdit(mainwindow)
        self.stepSize.setGeometry(QtCore.QRect(680, 610, 51, 21))
        self.stepSize.setObjectName("stepSize")
        self.addBreakpoint = QtWidgets.QLineEdit(mainwindow)
        self.addBreakpoint.setGeometry(QtCore.QRect(900, 560, 61, 21))
        self.addBreakpoint.setObjectName("addBreakpoint")
        self.removeBreakpoint = QtWidgets.QLineEdit(mainwindow)
        self.removeBreakpoint.setGeometry(QtCore.QRect(900, 600, 61, 21))
        self.removeBreakpoint.setObjectName("removeBreakpoint")
        self.currentCycle = QtWidgets.QLineEdit(mainwindow)
        self.currentCycle.setGeometry(QtCore.QRect(660, 550, 71, 41))
        self.currentCycle.setText("")
        self.currentCycle.setReadOnly(True)
        self.currentCycle.setObjectName("currentCycle")
        self.currentBreakpoints = QtWidgets.QTextEdit(mainwindow)
        self.currentBreakpoints.setGeometry(QtCore.QRect(980, 570, 131, 61))
        self.currentBreakpoints.setReadOnly(True)
        self.currentBreakpoints.setObjectName("currentBreakpoints")

        self.retranslateUi(mainwindow)
        self.tabs.setCurrentIndex(0)
        self.dataTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "Dialog"))
        self.stepButton.setText(_translate("mainwindow", "Step 1 cycle"))
        self.tabs.setTabText(self.tabs.indexOf(self.codeTab), _translate("mainwindow", "Code"))
        self.tabs.setTabText(self.tabs.indexOf(self.animationTab), _translate("mainwindow", "Animation"))
        self.stepBreakpointButton.setText(_translate("mainwindow", "Step until next breakpoint"))
        self.title.setText(_translate("mainwindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">ELISA: EducationaL Instruction Set Architecture</span></p><p align=\"center\"><span style=\" font-size:18pt;\">Josh Sennett &amp; Yash Adhikari -- CMPSCI 535: Computer Architecture</span></p></body></html>"))
        self.importButton.setText(_translate("mainwindow", "Import"))
        self.exportButton.setText(_translate("mainwindow", "Export"))
        self.currentBreakpointsLabel.setText(_translate("mainwindow", "<html><head/><body><p><span style=\" font-weight:600;\">Current Breakpoints</span></p></body></html>"))
        self.addBreakpointButton.setText(_translate("mainwindow", "Add Breakpoint"))
        self.stepNCyclesButton.setText(_translate("mainwindow", "Step N cycles"))
        self.resetButton.setText(_translate("mainwindow", "Reset"))
        self.currentCycleLabel.setText(_translate("mainwindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Current Cycle:</span></p></body></html>"))
        self.stepCompletionButton.setText(_translate("mainwindow", "Step until completion"))
        self.registerTable.setSortingEnabled(False)
        item = self.registerTable.verticalHeaderItem(0)
        item.setText(_translate("mainwindow", "0"))
        item = self.registerTable.verticalHeaderItem(1)
        item.setText(_translate("mainwindow", "1"))
        item = self.registerTable.verticalHeaderItem(2)
        item.setText(_translate("mainwindow", "2"))
        item = self.registerTable.verticalHeaderItem(3)
        item.setText(_translate("mainwindow", "3"))
        item = self.registerTable.verticalHeaderItem(4)
        item.setText(_translate("mainwindow", "4"))
        item = self.registerTable.verticalHeaderItem(5)
        item.setText(_translate("mainwindow", "5"))
        item = self.registerTable.verticalHeaderItem(6)
        item.setText(_translate("mainwindow", "6"))
        item = self.registerTable.verticalHeaderItem(7)
        item.setText(_translate("mainwindow", "7"))
        item = self.registerTable.verticalHeaderItem(8)
        item.setText(_translate("mainwindow", "8"))
        item = self.registerTable.verticalHeaderItem(9)
        item.setText(_translate("mainwindow", "9"))
        item = self.registerTable.verticalHeaderItem(10)
        item.setText(_translate("mainwindow", "10"))
        item = self.registerTable.verticalHeaderItem(11)
        item.setText(_translate("mainwindow", "11"))
        item = self.registerTable.verticalHeaderItem(12)
        item.setText(_translate("mainwindow", "12"))
        item = self.registerTable.verticalHeaderItem(13)
        item.setText(_translate("mainwindow", "13"))
        item = self.registerTable.verticalHeaderItem(14)
        item.setText(_translate("mainwindow", "14"))
        item = self.registerTable.verticalHeaderItem(15)
        item.setText(_translate("mainwindow", "15"))
        item = self.registerTable.verticalHeaderItem(16)
        item.setText(_translate("mainwindow", "16"))
        item = self.registerTable.verticalHeaderItem(17)
        item.setText(_translate("mainwindow", "17"))
        item = self.registerTable.verticalHeaderItem(18)
        item.setText(_translate("mainwindow", "18"))
        item = self.registerTable.verticalHeaderItem(19)
        item.setText(_translate("mainwindow", "19"))
        item = self.registerTable.verticalHeaderItem(20)
        item.setText(_translate("mainwindow", "20"))
        item = self.registerTable.verticalHeaderItem(21)
        item.setText(_translate("mainwindow", "21"))
        item = self.registerTable.verticalHeaderItem(22)
        item.setText(_translate("mainwindow", "22"))
        item = self.registerTable.verticalHeaderItem(23)
        item.setText(_translate("mainwindow", "23"))
        item = self.registerTable.verticalHeaderItem(24)
        item.setText(_translate("mainwindow", "24"))
        item = self.registerTable.verticalHeaderItem(25)
        item.setText(_translate("mainwindow", "25"))
        item = self.registerTable.verticalHeaderItem(26)
        item.setText(_translate("mainwindow", "26"))
        item = self.registerTable.verticalHeaderItem(27)
        item.setText(_translate("mainwindow", "27"))
        item = self.registerTable.verticalHeaderItem(28)
        item.setText(_translate("mainwindow", "28"))
        item = self.registerTable.verticalHeaderItem(29)
        item.setText(_translate("mainwindow", "29"))
        item = self.registerTable.verticalHeaderItem(30)
        item.setText(_translate("mainwindow", "30"))
        item = self.registerTable.verticalHeaderItem(31)
        item.setText(_translate("mainwindow", "31"))
        item = self.registerTable.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "$R - Integer Registers"))
        item = self.registerTable.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "$F - Floating Point Registers"))
        __sortingEnabled = self.registerTable.isSortingEnabled()
        self.registerTable.setSortingEnabled(False)
        item = self.registerTable.item(32, 0)
        item.setText(_translate("mainwindow", "01101001011010010110100101101001"))
        item = self.registerTable.item(32, 1)
        item.setText(_translate("mainwindow", "01101001011010010110100101101001"))
        self.registerTable.setSortingEnabled(__sortingEnabled)
        self.dataTabs.setTabText(self.dataTabs.indexOf(self.registerTab), _translate("mainwindow", "Registers"))
        item = self.memoryTable.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "Address"))
        item = self.memoryTable.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "Value"))
        __sortingEnabled = self.memoryTable.isSortingEnabled()
        self.memoryTable.setSortingEnabled(False)
        self.memoryTable.setSortingEnabled(__sortingEnabled)
        self.dataTabs.setTabText(self.dataTabs.indexOf(self.memoryTab), _translate("mainwindow", "Memory"))
        item = self.cacheTable.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "Level"))
        item = self.cacheTable.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "Tag"))
        item = self.cacheTable.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow", "Index"))
        item = self.cacheTable.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow", "Valid"))
        item = self.cacheTable.horizontalHeaderItem(4)
        item.setText(_translate("mainwindow", "Word 1"))
        item = self.cacheTable.horizontalHeaderItem(5)
        item.setText(_translate("mainwindow", "Word 2"))
        item = self.cacheTable.horizontalHeaderItem(6)
        item.setText(_translate("mainwindow", "Word 3"))
        item = self.cacheTable.horizontalHeaderItem(7)
        item.setText(_translate("mainwindow", "Word 4"))
        __sortingEnabled = self.cacheTable.isSortingEnabled()
        self.cacheTable.setSortingEnabled(False)
        item = self.cacheTable.item(0, 0)
        item.setText(_translate("mainwindow", "L1"))
        item = self.cacheTable.item(0, 2)
        item.setText(_translate("mainwindow", "000"))
        item = self.cacheTable.item(0, 3)
        item.setText(_translate("mainwindow", "1"))
        item = self.cacheTable.item(0, 4)
        item.setText(_translate("mainwindow", "101010010010101101001"))
        item = self.cacheTable.item(0, 5)
        item.setText(_translate("mainwindow", "101010010010101101001"))
        item = self.cacheTable.item(0, 6)
        item.setText(_translate("mainwindow", "101010010010101101001"))
        item = self.cacheTable.item(0, 7)
        item.setText(_translate("mainwindow", "101010010010101101001"))
        item = self.cacheTable.item(1, 0)
        item.setText(_translate("mainwindow", "L1"))
        item = self.cacheTable.item(1, 2)
        item.setText(_translate("mainwindow", "001"))
        item = self.cacheTable.item(1, 3)
        item.setText(_translate("mainwindow", "1"))
        item = self.cacheTable.item(1, 4)
        item.setText(_translate("mainwindow", "101010010010101101001"))
        item = self.cacheTable.item(1, 5)
        item.setText(_translate("mainwindow", "101010010010101101001"))
        item = self.cacheTable.item(1, 6)
        item.setText(_translate("mainwindow", "101010010010101101001"))
        item = self.cacheTable.item(1, 7)
        item.setText(_translate("mainwindow", "101010010010101101001"))
        item = self.cacheTable.item(2, 0)
        item.setText(_translate("mainwindow", "L2"))
        item = self.cacheTable.item(2, 3)
        item.setText(_translate("mainwindow", "0"))
        item = self.cacheTable.item(3, 0)
        item.setText(_translate("mainwindow", "L2"))
        item = self.cacheTable.item(3, 3)
        item.setText(_translate("mainwindow", "0"))
        item = self.cacheTable.item(4, 0)
        item.setText(_translate("mainwindow", "L3"))
        item = self.cacheTable.item(4, 3)
        item.setText(_translate("mainwindow", "0"))
        item = self.cacheTable.item(5, 0)
        item.setText(_translate("mainwindow", "L3"))
        item = self.cacheTable.item(5, 3)
        item.setText(_translate("mainwindow", "0"))
        self.cacheTable.setSortingEnabled(__sortingEnabled)
        self.dataTabs.setTabText(self.dataTabs.indexOf(self.cacheTab), _translate("mainwindow", "Cache"))
        self.memoryDisplayLabel.setText(_translate("mainwindow", "Display Format"))
        self.memoryDisplayBox.setItemText(0, _translate("mainwindow", "Binary"))
        self.memoryDisplayBox.setItemText(1, _translate("mainwindow", "Hexadecimal"))
        self.memoryDisplayBox.setItemText(2, _translate("mainwindow", "Decimal"))
        self.removeBreakpointButton.setText(_translate("mainwindow", "Remove Breakpoint"))
        self.groupBox.setTitle(_translate("mainwindow", "GroupBox"))
        self.setConfigurationButton.setText(_translate("mainwindow", "Set Configuration"))
        self.L1Enabled.setText(_translate("mainwindow", "L1 Cache Enabled"))
        self.L1AssociativityLabel.setText(_translate("mainwindow", "Assoc."))
        self.L1Associativity.setItemText(0, _translate("mainwindow", "Direct-Mapped"))
        self.L1Associativity.setItemText(1, _translate("mainwindow", "2-Way"))
        self.L1Associativity.setItemText(2, _translate("mainwindow", "4-Way"))
        self.L1Associativity.setItemText(3, _translate("mainwindow", "8-Way"))
        self.L1Associativity.setItemText(4, _translate("mainwindow", "16-Way"))
        self.L1Associativity.setItemText(5, _translate("mainwindow", "32-Way"))
        self.L1Associativity.setItemText(6, _translate("mainwindow", "N-Way"))
        self.L1LinesLabel.setText(_translate("mainwindow", "# Lines"))
        self.L1Lines.setText(_translate("mainwindow", "8"))
        self.L1WordsPerLineLabel.setText(_translate("mainwindow", "Words/Line"))
        self.L1WordsPerLine.setItemText(0, _translate("mainwindow", "1"))
        self.L1WordsPerLine.setItemText(1, _translate("mainwindow", "2"))
        self.L1WordsPerLine.setItemText(2, _translate("mainwindow", "4"))
        self.L1WordsPerLine.setItemText(3, _translate("mainwindow", "8"))
        self.L1WordsPerLine.setItemText(4, _translate("mainwindow", "16"))
        self.L1WordsPerLine.setItemText(5, _translate("mainwindow", "32"))
        self.L1CyclesLabel.setText(_translate("mainwindow", "# Cycles"))
        self.L1Cycles.setText(_translate("mainwindow", "1"))
        self.writePolicyLabel.setText(_translate("mainwindow", "Write Policy:"))
        self.L2Enabled.setText(_translate("mainwindow", "L2 Cache Enabled"))
        self.L2AssociativityLabel.setText(_translate("mainwindow", "Assoc."))
        self.L2Associativity.setItemText(0, _translate("mainwindow", "Direct-Mapped"))
        self.L2Associativity.setItemText(1, _translate("mainwindow", "2-Way"))
        self.L2Associativity.setItemText(2, _translate("mainwindow", "4-Way"))
        self.L2Associativity.setItemText(3, _translate("mainwindow", "8-Way"))
        self.L2Associativity.setItemText(4, _translate("mainwindow", "16-Way"))
        self.L2Associativity.setItemText(5, _translate("mainwindow", "32-Way"))
        self.L2Associativity.setItemText(6, _translate("mainwindow", "N-Way"))
        self.L2LinesLabel.setText(_translate("mainwindow", "# Lines"))
        self.L2Lines.setText(_translate("mainwindow", "32"))
        self.L2WordsPerLineLabel.setText(_translate("mainwindow", "Words/Line"))
        self.L2WordsPerLine.setItemText(0, _translate("mainwindow", "1"))
        self.L2WordsPerLine.setItemText(1, _translate("mainwindow", "2"))
        self.L2WordsPerLine.setItemText(2, _translate("mainwindow", "4"))
        self.L2WordsPerLine.setItemText(3, _translate("mainwindow", "8"))
        self.L2WordsPerLine.setItemText(4, _translate("mainwindow", "16"))
        self.L2WordsPerLine.setItemText(5, _translate("mainwindow", "32"))
        self.L2CyclesLabel.setText(_translate("mainwindow", "# Cycles"))
        self.L2Cycles.setText(_translate("mainwindow", "1"))
        self.writePolicyBox.setItemText(0, _translate("mainwindow", "Write-through"))
        self.writePolicyBox.setItemText(1, _translate("mainwindow", "Write-back"))
        self.evictionPolicyLabel.setText(_translate("mainwindow", "Eviction Policy:"))
        self.evictionPolicyBox.setItemText(0, _translate("mainwindow", "LRU"))
        self.evictionPolicyBox.setItemText(1, _translate("mainwindow", "Random"))
        self.L3Enabled.setText(_translate("mainwindow", "L3 Cache Enabled"))
        self.L3AssociativityLabel.setText(_translate("mainwindow", "Assoc."))
        self.L3Associativity.setItemText(0, _translate("mainwindow", "Direct-Mapped"))
        self.L3Associativity.setItemText(1, _translate("mainwindow", "2-Way"))
        self.L3Associativity.setItemText(2, _translate("mainwindow", "4-Way"))
        self.L3Associativity.setItemText(3, _translate("mainwindow", "8-Way"))
        self.L3Associativity.setItemText(4, _translate("mainwindow", "16-Way"))
        self.L3Associativity.setItemText(5, _translate("mainwindow", "32-Way"))
        self.L3Associativity.setItemText(6, _translate("mainwindow", "N-Way"))
        self.L3LinesLabel.setText(_translate("mainwindow", "# Lines"))
        self.L3Lines.setText(_translate("mainwindow", "128"))
        self.L3WordsPerLineLabel.setText(_translate("mainwindow", "Words/Line"))
        self.L3WordsPerLine.setItemText(0, _translate("mainwindow", "1"))
        self.L3WordsPerLine.setItemText(1, _translate("mainwindow", "2"))
        self.L3WordsPerLine.setItemText(2, _translate("mainwindow", "4"))
        self.L3WordsPerLine.setItemText(3, _translate("mainwindow", "8"))
        self.L3WordsPerLine.setItemText(4, _translate("mainwindow", "16"))
        self.L3WordsPerLine.setItemText(5, _translate("mainwindow", "32"))
        self.L3CyclesLabel.setText(_translate("mainwindow", "# Cycles"))
        self.L3Cycles.setText(_translate("mainwindow", "3"))
        self.memoryLinesLabel.setText(_translate("mainwindow", "Memory Address Space: 2^"))
        self.memoryLines.setText(_translate("mainwindow", "12"))
        self.memoryCyclesLabel.setText(_translate("mainwindow", "# Cycles to access Memory"))
        self.memoryCycles.setText(_translate("mainwindow", "100"))
        self.pipelineEnabledButton.setText(_translate("mainwindow", "Pipelining Enabled"))
        self.NCyclesLabel.setText(_translate("mainwindow", "N:"))
        self.stepSize.setText(_translate("mainwindow", "1"))
        self.addBreakpoint.setText(_translate("mainwindow", "1"))
        self.removeBreakpoint.setText(_translate("mainwindow", "1"))

from codeeditor import CodeEditor
